/** @format */

import type { Metadata } from 'next'
import { Michroma, Roboto } from 'next/font/google'
import './globals.css'

const michroma = Michroma({
	weight: '400',
	variable: '--font-michroma',
	subsets: ['latin']
})

const roboto = Roboto({
	weight: ['400', '700'],
	variable: '--font-roboto',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${roboto.variable} ${michroma.variable} antialiased`}>{children}</body>
		</html>
	)
}
